"""empty message

Revision ID: 4140e80fb9ac
Revises: bd5355cf8263
Create Date: 2023-01-28 23:56:40.535508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4140e80fb9ac'
down_revision = 'bd5355cf8263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
